### ISSUE TITLE
the problem of data

### ISSUE THREAD

**Issue by makalo** [SilvioGiancola/ShapeCompletion3DTracking#1]
I'm glad you contributed to 3D tracking. When I run your code, I see that the category names are "Car" and there are errors. I think maybe the data structure I downloaded is different from yours. Can I publish the tree structure of the data path?

**Comment by SilvioGiancola** [comment]
Hi @makalo ,
I have updated the `readme.md` with the instruction to download [KITTI Tracking](http://www.cvlibs.net/datasets/kitti/eval_tracking.php):

You will need to download the data for [velodyne](http://www.cvlibs.net/download.php?file=data_tracking_velodyne.zip), [calib](http://www.cvlibs.net/download.php?file=data_tracking_calib.zip) and [label_02](http://www.cvlibs.net/download.php?file=data_tracking_label_2.zip).

Place the 3 folders in the same parent folder as following:
```
[Parent Folder]
--> [calib]
    --> {0000-0020}.txt
--> [label_02]
    --> {0000-0020}.txt
--> [velodyne]
    --> [0000-0020] folders with velodynes .bin files
```

Let me know if you still have any issue after that.
