### ISSUE TITLE
I want to know your method wehther or not could run in teal-time?

### ISSUE THREAD

**Issue by StiphyJay** [SilvioGiancola/ShapeCompletion3DTracking#10]
Thanks for you code and paper, your work is very outstanding. Here I have a few questions want to know and hope you could answer them. Did your method run in real-time?  if  could,  what speed and the corresponding device? If the search space in the front section of the network is not considered, how fast can it run?

**Comment by SilvioGiancola** [comment]
Dear @StiphyJay, those details are on the [paper](https://arxiv.org/pdf/1903.01784.pdf) in page 8, paragraph on **timing**. As we mentioned, PointNet is extremely fast and it takes only 1.8ms to evaluate the 147 candidates. Note that we were using a GX1080Ti (11GB) on pytorch 0.4.1.

**Comment by StiphyJay** [comment]
> Dear @StiphyJay, those details are on the [paper](https://arxiv.org/pdf/1903.01784.pdf) in page 8, paragraph on **timing**. As we mentioned, PointNet is extremely fast and it takes only 1.8ms to evaluate the 147 candidates. Note that we were using a GX1080Ti (11GB) on pytorch 0.4.1.

Thanks for your reply. I  just want to know what is the running time of your entire network from a given model shape and candidate shape to output final tracking results? Is it the parameter 'data_time' in your code? I would appreciate it if you could answer it for me! Thank you very much.

**Comment by SilvioGiancola** [comment]
It is [batch_time](https://github.com/SilvioGiancola/ShapeCompletion3DTracking/blob/b4648ac67e9ba16ef986c58e021c6b52ae6ffd4e/code/train.py#L155) for the whole batch. 

[data_time](https://github.com/SilvioGiancola/ShapeCompletion3DTracking/blob/b4648ac67e9ba16ef986c58e021c6b52ae6ffd4e/code/train.py#L123) is the time for the data to be loaded, as the comments suggest.
