### ISSUE TITLE
Parameter setting when deploy

### ISSUE THREAD

**Issue by jiayily** [SilvioGiancola/ShapeCompletion3DTracking#11]
Hi, thanks for your nice work. I have some doubts when I'm trying to deploy it on my own data. What I want is to track a car, and I only have a detected 3d bounding box at the first frame. So I set reference_BB="previous_result" and search_space="kalman". But I get a poor performance. The same as I change search_space to Particle filter. What makes me confused is that, the Siamese network seems only play a role that pick the most similar candidate from kalman filter's predictions when infer? So the performance is sensitive to kalman filter's predictions?

**Comment by SilvioGiancola** [comment]
Yes @crazyliyi , we treated tracking as a combination of search space (exhaustive, KF, PF, ...) and model representation (Siamese Network). The latter is obviously conditioned by the design of the former. An improved search space would lead into better proposals, hence better performances.
