### ISSUE TITLE
How to visualize object tracking results using your module on entire pointcloud?

### ISSUE THREAD

**Issue by ghost** [SilvioGiancola/ShapeCompletion3DTracking#4]
@SilvioGiancola ,
How to visualize object tracking results using your module on entire pointcloud? Kindly help

**Comment by SilvioGiancola** [comment]
Dear @sankhanrsss ,
We recently added a [tool](https://github.com/SilvioGiancola/ShapeCompletion3DTracking#visualize-the-results) to visualize the tracking results, as well as the reconstruction quality in time.
Cheers,
