### ISSUE TITLE
Settings of training on other categories

### ISSUE THREAD

**Issue by HaozheQi** [SilvioGiancola/ShapeCompletion3DTracking#7]
Hi, thanks for your work on 3D tracking with the code. 
I want to train the model on other categoties as well, such as pedestrain. I wander if I can just use the order 
python main.py --train_model --model_name=<Name of your model> --dataset_path=<Path to KITTI Tracking folder> --category_name="Pedestrain"
to train on padestrain or I need to make other changes?

**Comment by SilvioGiancola** [comment]
Hi @ZeyangZhang1,
Yes, you should be able to train on more categories, such as pedestrian and cyclist. Is has been done [here](https://arxiv.org/pdf/1903.10168.pdf) (Table 3 and 4).
All you need to do is specify `--category_name="Pedestrian"` and set `--args.model_path=""`, else it will fine-tune the model pre-trained on cars. 
If I remember well, in our follow up analysis we dropped the pre-training for those classes as pre-training was not that important.

**Comment by HaozheQi** [comment]
Thank you very much for your reply. It helps me a lot!
