### ISSUE TITLE
Which coordinate do you use?

### ISSUE THREAD

**Issue by KinglittleQ** [SilvioGiancola/ShapeCompletion3DTracking#8]
In KITTI, there are Velodyne, reference camera and rectangle camera coordinates. Which coordinate do you use before feeding the point cloud into the network?

And why you do add a rotation of pi/2 at x-axis [here](https://github.com/SilvioGiancola/ShapeCompletion3DTracking/blob/b4648ac67e9ba16ef986c58e021c6b52ae6ffd4e/code/Dataset.py#L89)?
``` python
    def getPCandBBfromPandas(self, box, calib):
        center = [box["x"], box["y"] - box["height"] / 2, box["z"]]
        size = [box["width"], box["length"], box["height"]]
        orientation = Quaternion(
            axis=[0, 1, 0], radians=box["rotation_y"]) * Quaternion(
                axis=[1, 0, 0], radians=np.pi / 2)
        BB = Box(center, size, orientation)
```

**Comment by jiayily** [comment]
I have the same doubt, can you give a detailed explanation about this? Thx

**Comment by ujaejoon** [comment]
@KinglittleQ @jiayily I have the same question and have been considering possible reasons, but I haven’t found an answer yet. If you know the reason why, I would be very grateful if you could share it with me.
