### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Model

### ISSUE THREAD

**Issue by WestbrookZero** [SilvioGiancola/ShapeCompletion3DTracking#9]
![problem01](https://user-images.githubusercontent.com/13358789/79324579-65c1f300-7f42-11ea-8cb6-a7b583f5c57e.png)
My path is right,when i run main.py ,it is error.

**Comment by SilvioGiancola** [comment]
Hi @WestbrookZero ,
Does that also happen with the other models `OnlyCompletion`, `OnlyTracking` or `Ours`?

**Comment by WestbrookZero** [comment]
when i use OnlyCompletion , my environment is win10、pytorch0.4.1、cuda10.0.
![problem02](https://user-images.githubusercontent.com/13358789/79408048-fb09c980-7fcc-11ea-8fe0-59529517941d.png)
 Is it possible to run this project successfully by using pytorch>=1.0 and cuda==10.0 ?

**Comment by SilvioGiancola** [comment]
This is now a different issue. I have never tried running this code on Windows, but your problem appear to be either in your CUDA libraries (`RuntimeError: Cannot pickle CUDA storage`), or in your input data (`EOFError: Ran out of input`).

Regarding the models, `Pretrained_ShapeNet` is always loaded by default. If you want to test the model `Pretrained_ShapeNet`, all you have to do is not load any other model by setting `--model_name` empty. If you want to test the models `OnlyCompletion`, `OnlyTracking` or `Ours`, you can pass that model in the argument `--model_name`.

Hope that helps.
